name: bitwarden-cli
version: "1.0.0"
summary: A secure and free password manager for all of your devices.
description: A secure and free password manager for all of your devices.
confinement: devmode
apps:
  bitwarden-cli:
    command: bw
    plugs: [network, home, x11]
parts:
  bitwarden-cli:
    plugin: nodejs
    node-engine: 9.7.1
    source: ../..
